### ISSUE TITLE
StringGenerator 0.3.0 does not successfully install with pip

### ISSUE THREAD

**Issue by ddeel** [paul-wolf/strgen#10]
On Windows 10 with Python 3.6.1, "pip install StringGenerator" gets the following error:

C:\Users\Don\Documents\test>pip install StringGenerator
Collecting StringGenerator
  Using cached https://files.pythonhosted.org/packages/71/31/97eeae37a7d1322d9bd12f73406afa522dfb1e6303e3f6504717e6c2f528/StringGenerator-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Don\AppData\Local\Temp\pip-install-2rxfgnzn\StringGenerator\setup.py", line 7, in <module>
        long_description = file.read()
      File "c:\users\don\documents\test\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1264: character maps to <undefined>

As a workaround, one can force pip to use the earlier version of StringGenerator, which successfully installs:

C:\Users\Don\Documents\test>pip install StringGenerator==0.2.1
Collecting StringGenerator==0.2.1
Installing collected packages: StringGenerator
Successfully installed StringGenerator-0.2.1

**Comment by paul-wolf** [comment]
Hmm, I'll need to look at that and maybe just get rid of that part of setup.py. I should be able to post a fix shortly.

**Comment by paul-wolf** [comment]
@ddeel: I had someone try this out with Windows and it seems to install fine. See below. Do you use any kind of custom encoding in your os ?

* OS Name:    Microsoft Windows 10 Pro
* Version:    10.0.17134 Build 17134
* 64-bit

```
akos@Akos-PC:~$ pip3 install StringGenerator
Collecting StringGenerator
  Using cached https://files.pythonhosted.org/packages/71/31/97eeae37a7d1322d9bd12f73406afa522dfb1e6303e3f6504717e6c2f528/StringGenerator-0.3.0.tar.gz
Building wheels for collected packages: StringGenerator
  Running setup.py bdist_wheel for StringGenerator ... done
  Stored in directory: /home/akos/.cache/pip/wheels/9e/1e/59/af26962bb40ff86890fe585e1a3409990d0fb9fcf15b81cd39
Successfully built StringGenerator
Installing collected packages: StringGenerator
Successfully installed StringGenerator
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.```

**Comment by paul-wolf** [comment]
Ok, I think I have found the problem. I replicated the issue:

```
with codecs.open("README.txt", 'rb', encoding="cp1252") as file:
    long_description = file.read()

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1264: character maps to <undefined>
```

and found at that position some characters I did not want, inverted quotes. I'll post a fix in a moment.

**Comment by paul-wolf** [comment]
@ddeel: I've uploaded a new 0.3.1 version that might fix your problems. Please let me know.

**Comment by ddeel** [comment]
The new version 0.3.1 installs successfully on a couple of Windows 10 64-bit systems now, and it works fine with the code that needed StringGenerator.

Thank you for the quick response!

**Comment by ddeel** [comment]
Closing because I believe the issue has been fixed.
