### ISSUE TITLE
Problem with encoding in setup.py

### ISSUE THREAD

**Issue by grigouze** [paul-wolf/strgen#12]
Hello.

The commit https://github.com/paul-wolf/strgen/commit/256489e855aa750b991d8bcb482ba04d67c1f91e#diff-2eeaed663bd0d25b7e608891384b7298 introduce a problem with python 2.X

TypeError: 'encoding' is an invalid keyword argument for this function

You have to remove the encoding if you want to be python 2.X compatible.

**Comment by paul-wolf** [comment]
@grigouze , thanks for that. I'll have a look. It passed all travis-ci tests, so I thought it was good.

**Comment by grigouze** [comment]
@paul-wolf maybe it's not testing setup.py :)

**Comment by paul-wolf** [comment]
@grigouze, you must be right. I'll try using `codecs.open()` or maybe `io.open()`.

**Comment by paul-wolf** [comment]
@grigouze, should be fixed now on version 0.3.3.

**Comment by grigouze** [comment]
@paul-wolf thanks
