### ISSUE TITLE
Providing a backslash within range does work

### ISSUE THREAD

**Issue by PyOctoCat** [paul-wolf/strgen#13]
According to the documentation you should provide three backslashes for this. I've tried various combination and none seem to work here is the test code.

rex_arg = r'\\'
rex_word = StringGenerator(rex_arg).render()
print('rex1', rex_word)
rex_arg = r'[\\\]'
rex_word = StringGenerator(rex_arg).render()
print('rex2', rex_word)

**Comment by paul-wolf** [comment]
hi @PyOctoCat , yes, you seem to be right. I'll investigate further and see if I can fix shortly.

**Comment by paul-wolf** [comment]
@PyOctoCat, I've published a fix for this to PyPi, version 0.3.4:

```
In [1]: from strgen import StringGenerator as SG
In [2]: SG(r"[\\]").render()
Out[2]: '\\'

In [3]: SG(r"[abc\\]{8}").render()
Out[3]: 'aabaa\\ba'
```
Not had time to further test different variations, but I hope this gets you further for now. Don't hesitate to let me know if you find any issues and thanks for using this module!

**Comment by PyOctoCat** [comment]
It looks like that fixed it. Thanks. Here is the sample of the range of text:

from strgen import StringGenerator
rex_arg = r'[a-zA-Z0-9 ~`!@#\$%^\&\*\(\)-_=+\[\{\}\];:"\'\|\\,<.>/?]{8-16}'
print(StringGenerator(rex_arg).render())

]Tsl\SfR/o7+\

**Comment by paul-wolf** [comment]
@PyOctoCat : glad that works for you!
