### ISSUE TITLE
Set seed

### ISSUE THREAD

**Issue by goulvenguillard-bib** [paul-wolf/strgen#15]
I didn’t see a way to set the seed ?  This should be easy to implement since the module uses `random`, and it would be a great improvement for reproducibility.

**Comment by paul-wolf** [comment]
@goulvenguillard-bib: That is a good point. Let me see what I can do.

**Comment by paul-wolf** [comment]
@goulvenguillard-bib: how does this work for you?

```
sg = SG("[\w]{10}&[\d]{10}", seed=9001)
```

In addition, there will be a parameter, `randomizer` to allow the user to provide their own random class.

**Comment by paul-wolf** [comment]
Specifically:

```
from strgen import StringGenerator as SG
In [40]: sg = SG("[\w]{10}&[\d]{10}", seed=9001)

In [41]: sg.render_list(10)
Out[41]:
['bp0sF84LJ98Jp4d198Z5',
 'g36945X7F8_016NR048y',
 'g84XWehY456EO5G1a623',
 'cX8Pg7ih2S5Y679153f3',
 'z5p6ha1c18yG2460DA4O',
 '578HC4_07I12Dw43oSs1',
 'M3W9MF_lH3906I14O502',
 '9t4Wt8v71hfZ54y01E41',
 '09XK8SV0cPh41E0l8384',
 '59Z5b2n98F99G8K79335']

In [42]: sg = SG("[\w]{10}&[\d]{10}", seed=9001)

In [43]: sg.render_list(10)
Out[43]:
['bp0sF84LJ98Jp4d198Z5',
 'g36945X7F8_016NR048y',
 'g84XWehY456EO5G1a623',
 'cX8Pg7ih2S5Y679153f3',
 'z5p6ha1c18yG2460DA4O',
 '578HC4_07I12Dw43oSs1',
 'M3W9MF_lH3906I14O502',
 '9t4Wt8v71hfZ54y01E41',
 '09XK8SV0cPh41E0l8384',
 '59Z5b2n98F99G8K79335']
```

**Comment by paul-wolf** [comment]
@goulvenguillard-bib: the seed feature is available on pypi:

https://pypi.org/project/StringGenerator/0.4.1/

Documentation: 

https://strgen.readthedocs.io/en/latest/randomizer.html

**Comment by goulvenguillard-bib** [comment]
Yes, that’s great, thanks for your reactivity !
