### ISSUE TITLE
Stringenerator latest release 0.4.1 fails with syntax error

### ISSUE THREAD

**Issue by aelumal** [paul-wolf/strgen#16]
![image](https://user-images.githubusercontent.com/63835354/110091711-c195a480-7dbe-11eb-9408-4d154cca4c7e.png)

**Comment by paul-wolf** [comment]
Apologies. Will post a fix in a few hours.

**Comment by paul-wolf** [comment]
hi @aelumal : StringGenerator no longer supports Python 2.7 but you can use version 0.3.4 or earlier.

**Comment by paul-wolf** [comment]
hi @aelumal, I've added a note to the start of both the readme and the online docs about the required version of Python. Many thanks for your interest in the project!
