### ISSUE TITLE
Missing period in __init__.py ? Python 3.4.3 64bit, Windows

### ISSUE THREAD

**Issue by JarrodAJ** [paul-wolf/strgen#5]
I received an import error whenever I tried to "import strgen" or "from strgen import StringGenerator". To resolve, edit  **init**.py in the strgen directory. All that's needed is a period in front of string_generator, as below: 

``` python
from .string_generator import StringGenerator
```

**Comment by paul-wolf** [comment]
Ok, I was able to confirm your experience on python 3.4 (it works fine on 2.x). I'll post a fix for this shortly.

**Comment by paul-wolf** [comment]
Fixed this on PyPi. `pip install --upgrade StringGenerator` to get fix. 

Tested on python 2.7.6 and 3.4.
