### ISSUE TITLE
missing return statement in last() function

### ISSUE THREAD

**Issue by YifanCao** [paul-wolf/strgen#6]
Hi, please check the last() function in your code, as following:

def last(self):
    if self.index == 0:
        return None
    self.pattern[self.index-1]

Notice that the last line should start with a "return" keyword... I think.

Thanks
Yifan

**Comment by paul-wolf** [comment]
Yes, that seems to be correct. Thanks for spotting that!

**Comment by paul-wolf** [comment]
Fixed this issue with version 1.6 now on pypi.
