### ISSUE TITLE
hypen character support is broken in version 0.1.9

### ISSUE THREAD

**Issue by jlirochon** [paul-wolf/strgen#7]
```
from strgen import StringGenerator
StringGenerator("hello-[\w]{8}")
...
SyntaxError: Un-escaped special character: -
```

We should be able to use hyphens outside of square brackets

**Comment by jlirochon** [comment]
0.1.7 : ok
0.1.8 : broken
0.1.9 : broken

**Comment by paul-wolf** [comment]
You are right. I'll post a fix very shortly.

**Comment by robert-cody** [comment]
Not yet?

**Comment by paul-wolf** [comment]
Yes, that was a long pause, @vit0rg. I will get on it.

**Comment by paul-wolf** [comment]
I've pushed StringGenerator 0.2.0 to PyPi

Firstly, sorry for the long delay on fixing this. 

It's now possible, again, to use hyphens outside of a class as a literal. No escaping necessary: 

```
python -c "from strgen import StringGenerator as SG; print(SG('--hello--[\w]{8}').render())"
--hello--qrF1uG4U
```
Hope that works for you. Thanks so much for your interest in this project.

**Comment by robert-cody** [comment]
@paul-wolf thanks a lot!

**Comment by paul-wolf** [comment]
@vit0rg: I am really grateful you took the time to get in touch. 

Let me know any other issues. I'll close this if there are not problems.

**Comment by robert-cody** [comment]
@paul-wolf yep, works fine in 0.2.0, thanks again.
